sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mjEuV9tb2s04k4Utpgoh+zxC0bvyYznGnI/qWMooWrzevBRPPr9pdTON/3HRzmxDgcx7lDseKM0654X1FODao4sj/HKJ3G1ByY0iN0ruJQ6cmEpMe3Zs9uuYCrmcjFOvDnqKIQhl2PlxgI1wnGLLAeDnugG6p1WFvC0XCK+Cx4SpWrL7WmmyVl6j+bY8F9dNso7U+bv+uxrLwdstHvPILZOEy+Cs2wnDyqUAeCXi0DjfhtZvL6MakprUmJZtglM+NO7KC8hlaeTICMxYZIecVDkGI0vGZiOu5F3oEtim4ZyiweayHtInkt0XmwhoYtPRw/FlHGKW4aFGeynRiLbJJNixPxIZMOa6dLPrh0EYz7y/uoYmdFOQst05WAin6GbQEar8tDGXzbYiuBEPE6KlWfJPZkn5lwoNSeE+D1KMKy0XetAYfLH2hSC2ARP26HdowvjabXzH3WMVZdBq1l0YgfN4oXpBRP8xoY7pO2itrlB5HAYI6kFVnkkrfThtsk1xvwcwMU0VphSwudHqyHbzgUl3Vr9jbl3EwFK3wRyzShQeNW4cVhy3is78qDvL60X0dmqRjhLI5pztvrcfTw2BF2g0UOvRw6DHZg7bXODXF2bs6wOWB1XayxrHPyHUgbHORhN8WxI598Yj24k/hgUzE3vyN2bo61hvwydjuFt674M=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Green-Fancy_5871
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy